//Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
// find the sum of the even-valued terms.
// -------------------------------------------- //

//Find all the numbers in the sequence
//set limit to 4 mil and find evens
//add and return value

let arr = [1,2]
let arr2 = []

const EvenSum = num => {
    // Implement the Fibonacci algorithm using the linear approach
    for (let i = 2; i <= num; i++) {
    //   console.log(i)
      arr.push(arr[i - 2] + arr[i - 1])
    }
    // To see normal array
    // console.log(arr)
    
    for (let i = 0; i <arr.length; i++){
        if (arr[i] % 2 === 0) {
            arr2.push(arr[i])
        }  
    }
    // To see array with only even #
    // console.log(arr2)
    
    var sum = arr2.reduce(function(a, b){
        return a + b;
    }, 0);
    return sum
  };
  
  console.log(EvenSum(40)); // => 40